/*
 *  Super Lead rope mod
 *  Copyright (C)  2026  R3944Realms
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package top.r3944realms.superleadrope.datagen.provider;

import net.minecraft.data.PackOutput;
import net.minecraftforge.client.model.generators.BlockStateProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import top.r3944realms.superleadrope.SuperLeadRope;

/**
 * The type Slp block state generator.
 */
public class SLPBlockStateGenerator extends BlockStateProvider {
    /**
     * Instantiates a new Slp block state generator.
     *
     * @param output       the output
     * @param exFileHelper the ex file helper
     */
    public SLPBlockStateGenerator(PackOutput output, ExistingFileHelper exFileHelper) {
        super(output, SuperLeadRope.MOD_ID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
    }
}