/*
 *  Super Lead rope mod
 *  Copyright (C)  2025  R3944Realms
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR 阿 PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package top.r3944realms.superleadrope.datagen.provider;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.world.item.Items;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import top.r3944realms.superleadrope.SuperLeadRope;
import top.r3944realms.superleadrope.content.SLPTags;

import java.util.concurrent.CompletableFuture;

/**
 * The type Slp item tag provider.
 */
public class SLPItemTagProvider extends ItemTagsProvider {
    /**
     * Instantiates a new Slp item tag provider.
     *
     * @param packOutput         the pack output
     * @param holderProvider     the holder provider
     * @param existingFileHelper the existing file helper
     */
    public SLPItemTagProvider(
            PackOutput packOutput,
            CompletableFuture<HolderLookup.Provider> holderProvider,
            @Nullable ExistingFileHelper existingFileHelper) {
        super(packOutput, holderProvider, CompletableFuture.completedFuture(TagLookup.empty()), SuperLeadRope.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        tag(SLPTags.Items.LEAD)
                .add(Items.LEAD)
                .add(Items.SLIME_BALL)
                .add(Items.STRING);
    }
}
